<a href="https://colab.research.google.com/github/MAbdullah005/Libaraycode/blob/main/matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import torch as p
import tensorflow as tf
a=np.array([[3,4],[5,6],[7,8]])
b=np.array([1,2])

np.dot(a,b)

array([11, 17, 23])

array([[25,  5,  3],
       [ 2, 26,  7]])

In [17]:
x=p.tensor([[3,4],[5,6],[7,8]])
a=p.tensor([1,2])
p.matmul(x,a)

tensor([11, 17, 23])

In [11]:
x*2+2

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[52,  6],
       [12, 54],
       [ 8, 16]], dtype=int32)>

In [18]:
x=tf.Variable([[3,4],[5,6],[7,8]])
a=tf.Variable([1,2])
tf.linalg.matvec(x,a)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([11, 17, 23], dtype=int32)>

### Reduction

calculating the sum across all the element of tensor is a common operation For exemple :
For a matrix **x**