<a href="https://colab.research.google.com/github/MAbdullah005/Libaraycode/blob/main/matrix%20inversion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Matrix inversion


*   4b+2c=4 ---1
*   -5b-3c=-7---2

 from equation 1 and 2 we can find the matric inversion



In [12]:
import numpy as np
import torch as p
import tensorflow as tf



*   where  x=[[4,2],[-5,-3]]

* y=[4,-7]


*   and we find the w values by applying matrix inverse

*  **Xw=y**

*   **w=X^-1*y**




In [14]:
x=np.array([[4,2],[-5,-3.]])
x

array([[ 4.,  2.],
       [-5., -3.]])

In [5]:
x_inverse=np.linalg.inv(x)
x_inverse

array([[ 1.5,  1. ],
       [-2.5, -2. ]])

In [7]:
y=np.array([4,-7])
y

array([ 4, -7])

In [8]:
w=np.dot(x_inverse,y)
w

array([-1.,  4.])

### Prove



*   We can prove of matrix inversion by equation
* **y=wX**





In [11]:
np.dot(x,w)

array([ 4., -7.])

### In Pytorch and Tensor flow

In [15]:
p.inverse(p.from_numpy(x))

tensor([[ 1.5000,  1.0000],
        [-2.5000, -2.0000]], dtype=torch.float64)

In [17]:
tf.linalg.inv(tf.Variable([[4,2],[-5,-3.]]))

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4999998,  0.9999998],
       [-2.4999995, -1.9999996]], dtype=float32)>

# Matrix invesion not possiable condition



*   there two condtition we can not peform matrix inversion



1.   When line are parallel where line equation are multiiple of each other so they are singular matrix
2.   when line are equall to each other so they can ont meat and lead to infinity in grapg




In [20]:
x=np.array([[-4,1],[-4,1]])
xinv=np.linalg.inv(x)
xinv

LinAlgError: Singular matrix

In [21]:
x=np.array([[-4,1],[-8,2]])
xinv=np.linalg.inv(x)
xinv

LinAlgError: Singular matrix