<a href="https://colab.research.google.com/github/MAbdullah005/Libaraycode/blob/main/Orthonologal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Orthonolagal Matrix

In [12]:
import numpy as np
I=np.array([[1,0,0],[0,1,0],[0,0,1]])
I

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
coloum_1=I[:,0]
coloum_1

array([1, 0, 0])

In [14]:
coloum_2=I[:,1]
coloum_2

array([0, 1, 0])

In [15]:
coloum_3=I[:,2]
coloum_3

array([0, 0, 1])

In [16]:
np.dot(coloum_1,coloum_2)

0

In [17]:
np.dot(coloum_1,coloum_3)

0

In [18]:
np.dot(coloum_2,coloum_3)

0



*   As we seen above the dot product of all coloum are equall to zero as we know dot product lead with cos function  and cos 0 is equall to 90 degree



we can also use np.linalg.norm() and each coloum I3 has unit norm

In [19]:
np.linalg.norm(coloum_1)

1.0

In [20]:
np.linalg.norm(coloum_2)

1.0

In [21]:
np.linalg.norm(coloum_3)

1.0