<a href="https://colab.research.google.com/github/MAbdullah005/Libaraycode/blob/main/systemiticmatrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Systemitic Matrix

Systematice Matrix is a matrix having a squared matrix
and the transpose of that matrix is must be equall to :

In [2]:
import numpy as np
x_sym=np.array([[0,1,2],[1,7,8],[2,8,9]])
x_sym

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [3]:
x_sym.T

array([[0, 1, 2],
       [1, 7, 8],
       [2, 8, 9]])

In [4]:
x_sym==x_sym.T

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

### Identity Matrix

In [5]:
import torch as p
a=p.tensor([[1,0,0],[0,1,0],[0,0,1]])
a

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])

In [6]:
b=p.tensor([25,2,5])
b

tensor([25,  2,  5])

In [7]:
p.matmul(a,b)

tensor([25,  2,  5])